version: 2.1
orbs:
  node: circleci/node@5.0.1
  # heroku: circleci/heroku@1.2.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
  docker-build-release:
    machine:
      enabled: true
    parameters:
      app-name:
        description: 'The Heroku app name to which the application should be deployed'
        type: string
      app-type:
        description: 'The Heroku app type (web or worker) of the application to be deployed'
        type: string
        default: 'web'
    steps:
      - checkout # Checkout code from github repository
      - run:
          name: View Files
          command: |
            ls -ll
      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Verify Container Login
          command: |
            heroku container:login
      - run:
          name: Build Docker Container
          command: |
            docker build --rm=false -t registry.heroku.com/<< parameters.app-name >>/<< parameters.app-type >> .
      - run:
          name: Push Container To Heroku
          command: |
            docker push registry.heroku.com/<< parameters.app-name >>/<< parameters.app-type >>
      - run:
          name: Release Deployed Container
          command: |
            heroku container:release << parameters.app-type >> -a << parameters.app-name >>

machine:
  services:
    - docker

dependencies:
  cache_directories:
    - ~/docker

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test

      # Staging [branch=staging]
      - docker-build-release:
          requires:
            - build-and-test
          app-name: '${APP_PREFIX}-staging'
          filters:
            branches:
              only: staging # Only run this build and deploy for staging branch.

      # Production [branch=master]
      - docker-build-release:
          requires:
            - build-and-test
          app-name: '${APP_PREFIX}-production'
          filters:
            branches:
              only: main # Only run this build and deploy for master branch.
  # build-and-test:
  #   jobs:
  #     - build-and-test
  # matrix-tests:
  #   jobs:
  #     - node/test:
  #         matrix:
  #           parameters:
  #             version:
  #               - 13.11.0
  #               - 12.16.0
  #   - heroku/deploy-via-git
